version: '2'
services:
  postgres:
    image: postgres:11.3
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=sarah
      - POSTGRES_PASSWORD=connor
      - POSTGRES_DB=mydatabase

  artemis:
    image: vromero/activemq-artemis:2.8.0-alpine
    ports:
      - "8161:8161"
      - "61616:61616"
      - "5672:5672"
    environment:
      ARTEMIS_USERNAME: quarkus
      ARTEMIS_PASSWORD: quarkus
      BROKER_CONFIG_MAX_DISK_USAGE: 99
